project_name: chart-releaser
builds:
  - main: cr/main.go
    binary: cr
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
    goos:
      - linux
      - darwin
      - windows
    ldflags:
      - >-
        -X github.com/helm/chart-releaser/cr/cmd.Version={{ .Tag }}
        -X github.com/helm/chart-releaser/cr/cmd.GitCommit={{ .Commit }}
        -X github.com/helm/chart-releaser/cr/cmd.BuildDate={{ .Date }}
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - cr
    skip_push: false
    dockerfile: Dockerfile
    image_templates:
      - quay.io/helmpack/chart-releaser:{{ .Tag }}
      - quay.io/helmpack/chart-releaser:latest
    build_flag_templates:
      - --label=org.label-schema.schema-version=1.0
      - --label=org.label-schema.version={{ .Version }}
      - --label=org.label-schema.name={{ .ProjectName }}
      - --label=org.label-schema.build-date={{ .Date }}
      - --label=org.label-schema.description='cr - The chart release tool'
      - --label=org.label-schema.vendor=Helm
brews:
  - tap:
      owner: helm
      name: homebrew-tap
    commit_author:
      name: helm-bot
      email: helm-bot@users.noreply.github.com
    folder: Formula
    homepage: https://github.com/helm/chart-releaser/
    description: Hosting Helm Charts via GitHub Pages and Releases
    test: |
      system "#{bin}/cr --version"
