[[constraint]]
  name = "github.com/Songmu/retry"
  version = "0.0.1"

[[constraint]]
  name = "github.com/google/go-github"
  version = "17.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.12.3"

[prune]
  go-tests = true
  unused-packages = true
